// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ0NedpdjU90ZJWzQhhseyPEA8i6-_NpU',
    appId: '1:805776827361:web:2fd7d7c822b873b08668a0',
    messagingSenderId: '805776827361',
    projectId: 'classbizz-7c21a',
    authDomain: 'classbizz-7c21a.firebaseapp.com',
    storageBucket: 'classbizz-7c21a.firebasestorage.app',
    measurementId: 'G-HQ3D6F6LXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn21WRJqIl-PwZCQZVe8LShD7Pui7imhc',
    appId: '1:805776827361:android:e7a9ae6b0d7a3f088668a0',
    messagingSenderId: '805776827361',
    projectId: 'classbizz-7c21a',
    storageBucket: 'classbizz-7c21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSXw1T3-kguvlKSbHkytYaxnEcMhWuhIs',
    appId: '1:805776827361:ios:36a86a61dc3b4e6f8668a0',
    messagingSenderId: '805776827361',
    projectId: 'classbizz-7c21a',
    storageBucket: 'classbizz-7c21a.firebasestorage.app',
    iosBundleId: 'com.example.classbizzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSXw1T3-kguvlKSbHkytYaxnEcMhWuhIs',
    appId: '1:805776827361:ios:36a86a61dc3b4e6f8668a0',
    messagingSenderId: '805776827361',
    projectId: 'classbizz-7c21a',
    storageBucket: 'classbizz-7c21a.firebasestorage.app',
    iosBundleId: 'com.example.classbizzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ0NedpdjU90ZJWzQhhseyPEA8i6-_NpU',
    appId: '1:805776827361:web:0e4b30778cc599348668a0',
    messagingSenderId: '805776827361',
    projectId: 'classbizz-7c21a',
    authDomain: 'classbizz-7c21a.firebaseapp.com',
    storageBucket: 'classbizz-7c21a.firebasestorage.app',
    measurementId: 'G-80Z726BVHL',
  );
}
